### ISSUE TITLE
PSD Operator K-smallest eigenvalues/eigenvectors

### ISSUE THREAD

**Issue by twmitchel** [pnkraemer/matfree#221]
Hello,

I'm curious if the bidiagonalization/tridiagonalization can be used to get an estimate of the k-smallest eigenvalue/eigenvector pairs of a PSD operator. 

Looks like you can estimate a partial SVD in `eig.py`. This seems to imply that the bidiag routine would give you a decomposition with which you could extract the _largest_ k eigenvalue/vector pairs. Is there a simple way to modify(?) the decomp or `eig `example that would allow you to retrieve the _smallest_ k eigenvalue pairs?

Thanks!

**Comment by pnkraemer** [comment]
Hi, thanks for reaching out :) That's a great question! 

Is it enough for your application to compute the $k$ largest eigenvalues of $-A$ instead of $A$? These values should be the negatives of the $k$ smallest eigenvalues of $A$. What do you think? :)

**Comment by twmitchel** [comment]
Yes, thanks! I was expecting that trick would come up. :) 

In this case, is bidiagonalization or tridiagonalization most suitable? 

I'm assuming the implementation would be like the `eig.py` example such that once the decomposition is called on $-A$ to get $-A \approx  U M U^T$, I could call `jax.lax..linalg.eigh` on $M$ to get the eigenvalue decomposition (up to a flip for ascending ordering). 

Is this correct?

Alternatively, if using the bidiagonal decomposition, would $M$ already be the diagonal matrix of eigenvalues for $-A$?

**Comment by pnkraemer** [comment]
> Alternatively, if using the bidiagonal decomposition, would M already be the diagonal matrix of eigenvalues for − A ?

I'm not sure what you mean here. Could you clarify maybe? (If this question is still open despite my other answers below).


> I'm assuming the implementation would be like the eig.py example such that once the decomposition is called on − A to get − A ≈ U M U T , I could call jax.lax..linalg.eigh on M to get the eigenvalue decomposition and then multiply by − 1 (up to a flip for ascending ordering).
> 
> Is this correct?

Sounds correct to me! 


> In this case, is bidiagonalization or tridiagonalization most suitable?

I would say this depends on your matrix. If it is symmetric, run tri-diagonalisation and combine it with `jnp.linalg.eigh`. If not, or if it is of the form $A=M^\top M$, run bi-diagonalisation and combine it with an SVD. Does that help?

**Comment by twmitchel** [comment]
Yes, thank you! 

One last point of clarification -- from the documentation, I'm struggling to understand which of the inputs to the decomposition control the "rank" of the decomposition, e.g. what parameter determines the value $k$ such that $-A \approx U M U^T$ with $U$ a $n \times k$ matrix and $M$ a $k \times k$ matrix.

In `eig.py`, I'm guessing its the dimension of the initial guess `v0` which determines $k$ such that `v0` is an $n \times k$ array. Is this correct? 

Additionally, are the decompositions inherently batch-able? For example, if I want to decompose a batch of operators $A$ in that $A$ represents a $b \times n \times n$ tensor, will the decompositions do this natively or do I need to wrap them in `jax.vmap`?

**Comment by twmitchel** [comment]
Wow, I figured out an implementation and this is _amazingly_ fast on huge sparse systems. Around 50 times faster than the `lobpcg` implementation in `jax.experimental.sparse`. Can't tell you how long I've been looking for something like this!

I'm curious if there is any obvious way that `tridiag_sym` could be further optimized specifically for symmetric eigendecompositions, but otherwise I'll close this issue. Would be very interested to hear your thoughts on this -- will be super useful for geometry processing, etc. 

Thanks again, this is fantastic stuff!

**Comment by pnkraemer** [comment]
Wow, lots to reply to :blush:  Let's go: 

> One last point of clarification -- from the documentation, I'm struggling to understand which of the inputs to the decomposition control the "rank" of the decomposition, e.g. what parameter determines the value k such that − A ≈ U M U T with U a n × k matrix and M a k × k matrix.
> 
> In eig.py, I'm guessing its the dimension of the initial guess v0 which determines k such that v0 is an n × k array. Is this correct?

Short answer: no. In `eig.py` [[link](https://pnkraemer.github.io/matfree/API_documentation/eig/)], it's called `depth`.
If you know how to improve the docs, I'm all ears! :) 

Longer answer: This parameter naming is a bit inconsistent at the moment; some decompositions call this `depth`, some `krylov_depth`. IIRC, some previous versions called this parameter `num_matvecs` and some called it `rank`. It's all the same. Since I struggle to choose between the options, this argument tends to be positional-only. That said, if you agree that `krylov_depth` is a little more informative than `depth`, we should probably use `krylov_depth` everywhere. What do you think? Do you have a strict preference for one of the names or even a different one (`krylov_rank` maybe?)?  Should we create a new issue about naming this parameter and then resolve things there?


> Additionally, are the decompositions inherently batch-able? For example, if I want to decompose a batch of operators A in that A represents a b × n × n tensor, will the decompositions do this natively or do I need to wrap them in jax.vmap?

Great question. All the decompositions in matfree are intended to operate along the lines of:
```python
decomp = tridiag_sym(**parameters)
Q, H, rest = decomp(matvec, v0, *params)
```
so if matvec is batch'able, a jax.vmap around decomp should be plenty:
```python
decomp = functools.partial(decomp, matvec)
Q_batched, H_batched, rest = jax.vmap(decomp)(v0_batched, *params_batched)
```
That said, `eig.py` does not adhere to this pattern (but I think it should). If you agree that this behaviour would be beneficial, should we create a new issue called "Make eig.svd_partial batchable" or so, and resolve this in a pull request?


> Wow, I figured out an implementation and this is amazingly fast on huge sparse systems. Around 50 times faster than the lobpcg implementation in jax.experimental.sparse for a 20K x 20K system! Can't tell you how long I've been looking for something like this!

This is awesome :rocket: :rocket: I believe we don't have an eigenvalue-tutorial yet, maybe you have an idea what we should put in there :blush: :blush: 


> One thing I noticed is that tridiag_sym is about 50x slower if the reortho flag is set to "full". Is this to be expected?

Yeah, that's kind of expected. Whether it's 50x or, say, 1.5x depends on hardware (I found full reorthogonalisation to be pretty cheap on GPU), but it's slower regardless. The adjoints are also cheaper if we don't reorthogonalise (Theorem 4.2, https://arxiv.org/pdf/2405.17277).


> I'm curious if there is any obvious way that tridiag_sym could be further optimized specifically for symmetric eigendecompositions, but otherwise I'll close this issue

Do you have something specific in mind?
